spring.application.name=Voxera

# Server
server.port=8080

# Logging
logging.level.root=INFO

# Actuator
management.endpoints.web.exposure.include=health,info

# Devtools
spring.devtools.restart.enabled=true

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/Voxera
spring.datasource.username=root
spring.datasource.password=DEIN_ECHTES_PASSWORT
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect